apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  generation: 13
  name: important-service
  namespace: argocd
spec:
  destination:
    namespace: important-service
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: chart
    repoURL: https://github.com/elationemr/important-service
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
